### PR TITLE
prettier or die

### PR DESCRIPTION
**Pull request by PoolloverNathan**
if you forget to run prettier you get an x of shame on your commit

### CODE REVIEW

**Review by nin0-dev — CHANGES_REQUESTED** [review]
1. wrong branch
2. use pnpm not npm
3. wrong branch

**Comment by PoolloverNathan** [comment]
> 1. wrong branch
> 2. use pnpm not npm
> 3. wrong branch

@nin0-dev what branch do I use?

**Comment by PoolloverNathan** [comment]
oh rerewrite

**Comment by PoolloverNathan** [comment]
image

**Comment by PoolloverNathan** [comment]
guhhhhh
image

**Review by nin0-dev — APPROVED** [review]

**Pull request merged**
